services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - HOMEPAGE_ALLOWED_HOSTS
    volumes:
      - /etc/homelab/homepage/config:/app/config
    networks:
      - homelab

networks:
  homelab:
    external: true
