---
- name: Deploy services
  hosts: docker_host
  become: true

  vars:
    apps_path: /apps/homelab/apps
    stacks:
      - postgres
      - monitoring
      - proxy
      - uptime-kuma
      - homepage

  tasks:
    - name: Pull latest changes
      git:
        repo: https://github.com/manoelrsneto/homelab.git
        dest: /apps/homelab
        update: true

    - name: Write monitoring .env
      copy:
        dest: "{{ apps_path }}/monitoring/.env"
        mode: "0600"
        content: |
          GF_SECURITY_ADMIN_USER={{ grafana_admin_user }}
          GF_SECURITY_ADMIN_PASSWORD={{ grafana_admin_password }}
      no_log: true

    - name: Write postgres .env
      copy:
        dest: "{{ apps_path }}/postgres/.env"
        mode: "0600"
        content: |
          POSTGRES_USER={{ postgres_user }}
          POSTGRES_PASSWORD={{ postgres_password }}
          POSTGRES_DB={{ postgres_db }}
      no_log: true

    - name: Deploy stacks
      command: docker compose up -d --pull always
      args:
        chdir: "{{ apps_path }}/{{ item }}"
      loop: "{{ stacks }}"
