name: Infra

on:
  push:
    branches: [main]
    paths: ["infra/**"]

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      TF_VAR_proxmox_url: ${{ secrets.PROXMOX_URL }}
      TF_VAR_proxmox_user: ${{ secrets.PROXMOX_USER }}
      TF_VAR_proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}
      TF_VAR_gateway: ${{ secrets.GATEWAY }}
      TF_VAR_pihole_ip: ${{ secrets.PIHOLE_IP }}
      TF_VAR_docker_host_ip: ${{ secrets.DOCKER_HOST_IP }}
      TF_VAR_ansible_public_key: ${{ secrets.ANSIBLE_SSH_PUBLIC_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Connect Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra

      - name: Terraform Plan
        run: terraform plan
        working-directory: infra

      - name: Install sshpass
        if: github.ref == 'refs/heads/main'
        run: sudo apt-get install -y sshpass

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: infra
